export type Drug = {
  name: string;
  ingredient: string;
  form: "tablet" | "capsule" | "drops" | "syrup" | "inhaler" | "injection" | "sachet";
  typicalDose: number;
  unit: string;
  instructions: string;
};

export const DRUG_CATALOG: Drug[] = [
  { name: "Tachipirina 1000", ingredient: "Paracetamolo", form: "tablet", typicalDose: 1000, unit: "mg", instructions: "A stomaco pieno, non superare 3 g/die" },
  { name: "Tachipirina 500", ingredient: "Paracetamolo", form: "tablet", typicalDose: 500, unit: "mg", instructions: "Al bisogno, massimo 3 volte al giorno" },
  { name: "Moment", ingredient: "Ibuprofene", form: "tablet", typicalDose: 400, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Oki", ingredient: "Ketoprofene sale di lisina", form: "sachet", typicalDose: 80, unit: "mg", instructions: "Sciogliere in acqua, a stomaco pieno" },
  { name: "Aspirina", ingredient: "Acido acetilsalicilico", form: "tablet", typicalDose: 500, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Cardioaspirin", ingredient: "Acido acetilsalicilico", form: "tablet", typicalDose: 100, unit: "mg", instructions: "Dopo pranzo, deglutire intera" },
  { name: "Amlodipina", ingredient: "Amlodipina", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Alla stessa ora ogni giorno" },
  { name: "Norvasc", ingredient: "Amlodipina", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Alla stessa ora ogni giorno" },
  { name: "Lisinopril", ingredient: "Lisinopril", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Al mattino, anche a digiuno" },
  { name: "Enapren", ingredient: "Enalapril", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Al mattino" },
  { name: "Triatec", ingredient: "Ramipril", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Alla stessa ora ogni giorno" },
  { name: "Lasix", ingredient: "Furosemide", form: "tablet", typicalDose: 25, unit: "mg", instructions: "Al mattino, può aumentare la diuresi" },
  { name: "Atorvastatina", ingredient: "Atorvastatina", form: "tablet", typicalDose: 20, unit: "mg", instructions: "Alla sera" },
  { name: "Torvast", ingredient: "Atorvastatina", form: "tablet", typicalDose: 20, unit: "mg", instructions: "Alla sera" },
  { name: "Simvastatina", ingredient: "Simvastatina", form: "tablet", typicalDose: 20, unit: "mg", instructions: "Alla sera" },
  { name: "Eutirox", ingredient: "Levotiroxina sodica", form: "tablet", typicalDose: 75, unit: "mcg", instructions: "A digiuno, 30 minuti prima di colazione" },
  { name: "Metformina", ingredient: "Metformina", form: "tablet", typicalDose: 500, unit: "mg", instructions: "A stomaco pieno, durante i pasti" },
  { name: "Gliclazide", ingredient: "Gliclazide", form: "tablet", typicalDose: 30, unit: "mg", instructions: "A colazione" },
  { name: "Lantus", ingredient: "Insulina glargine", form: "injection", typicalDose: 12, unit: "UI", instructions: "Sempre alla stessa ora, ruotare il sito" },
  { name: "NovoRapid", ingredient: "Insulina aspart", form: "injection", typicalDose: 6, unit: "UI", instructions: "Subito prima dei pasti" },
  { name: "Pantoprazolo", ingredient: "Pantoprazolo", form: "tablet", typicalDose: 20, unit: "mg", instructions: "30 minuti prima di colazione" },
  { name: "Pantorc", ingredient: "Pantoprazolo", form: "tablet", typicalDose: 20, unit: "mg", instructions: "30 minuti prima di colazione" },
  { name: "Omeprazolo", ingredient: "Omeprazolo", form: "capsule", typicalDose: 20, unit: "mg", instructions: "Prima di colazione" },
  { name: "Lansoprazolo", ingredient: "Lansoprazolo", form: "capsule", typicalDose: 15, unit: "mg", instructions: "Prima di colazione" },
  { name: "Augmentin", ingredient: "Amoxicillina / acido clavulanico", form: "tablet", typicalDose: 875, unit: "mg", instructions: "A stomaco pieno, completare il ciclo" },
  { name: "Amoxicillina", ingredient: "Amoxicillina", form: "capsule", typicalDose: 1000, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Ventolin", ingredient: "Salbutamolo", form: "inhaler", typicalDose: 100, unit: "mcg", instructions: "1–2 puff, agitare prima dell'uso" },
  { name: "Clenil", ingredient: "Beclometasone", form: "inhaler", typicalDose: 250, unit: "mcg", instructions: "Risciacquare la bocca dopo l'uso" },
  { name: "Coumadin", ingredient: "Warfarin", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Alla stessa ora, controllo INR" },
  { name: "Eliquis", ingredient: "Apixaban", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Due volte al giorno, con o senza cibo" },
  { name: "Xarelto", ingredient: "Rivaroxaban", form: "tablet", typicalDose: 20, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Zoloft", ingredient: "Sertralina", form: "tablet", typicalDose: 50, unit: "mg", instructions: "Al mattino, con o senza cibo" },
  { name: "Xanax", ingredient: "Alprazolam", form: "tablet", typicalDose: 0.25, unit: "mg", instructions: "Secondo prescrizione, non sospendere bruscamente" },
  { name: "Tavor", ingredient: "Lorazepam", form: "tablet", typicalDose: 1, unit: "mg", instructions: "Alla sera se prescritto per il sonno" },
  { name: "Deltacortene", ingredient: "Prednisone", form: "tablet", typicalDose: 25, unit: "mg", instructions: "Al mattino, a stomaco pieno" },
  { name: "Bentelan", ingredient: "Betametasone", form: "tablet", typicalDose: 1, unit: "mg", instructions: "Secondo schema del medico" },
  { name: "Enterogermina", ingredient: "Bacillus clausii", form: "capsule", typicalDose: 2, unit: "mld", instructions: "Lontano dagli antibiotici di almeno 2 ore" },
  { name: "Buscopan", ingredient: "Scopolamina butilbromuro", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Al bisogno per crampi addominali" },
  { name: "Maalox", ingredient: "Alluminio / magnesio idrossido", form: "syrup", typicalDose: 10, unit: "ml", instructions: "Dopo i pasti o al bisogno" },
  { name: "Dibase", ingredient: "Colecalciferolo (vitamina D3)", form: "drops", typicalDose: 25, unit: "gocce", instructions: "Una volta a settimana, a stomaco pieno" },
  { name: "Clexane", ingredient: "Enoxaparina", form: "injection", typicalDose: 4000, unit: "UI", instructions: "Sottocute, ruotare la sede" },
  { name: "Tiklid", ingredient: "Ticlopidina", form: "tablet", typicalDose: 250, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Plavix", ingredient: "Clopidogrel", form: "tablet", typicalDose: 75, unit: "mg", instructions: "Alla stessa ora ogni giorno" },
  { name: "Sintrom", ingredient: "Acenocumarolo", form: "tablet", typicalDose: 4, unit: "mg", instructions: "Alla stessa ora, controllo INR" },
  { name: "Ciproxin", ingredient: "Ciprofloxacina", form: "tablet", typicalDose: 500, unit: "mg", instructions: "Lontano da latte e antiacidi" },
  { name: "Nexium", ingredient: "Esomeprazolo", form: "tablet", typicalDose: 20, unit: "mg", instructions: "Prima di colazione" },
  { name: "Concor", ingredient: "Bisoprololo", form: "tablet", typicalDose: 2.5, unit: "mg", instructions: "Al mattino, controllo frequenza" },
  { name: "Seloken", ingredient: "Metoprololo", form: "tablet", typicalDose: 50, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Dilatrend", ingredient: "Carvedilolo", form: "tablet", typicalDose: 6.25, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Coverlam", ingredient: "Perindopril / amlodipina", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Al mattino" },
  { name: "Zestril", ingredient: "Lisinopril", form: "tablet", typicalDose: 20, unit: "mg", instructions: "Al mattino, anche a digiuno" },
  { name: "Micardis", ingredient: "Telmisartan", form: "tablet", typicalDose: 40, unit: "mg", instructions: "Alla stessa ora ogni giorno" },
  { name: "Cozaar", ingredient: "Losartan", form: "tablet", typicalDose: 50, unit: "mg", instructions: "Alla stessa ora ogni giorno" },
  { name: "Diovan", ingredient: "Valsartan", form: "tablet", typicalDose: 80, unit: "mg", instructions: "Alla stessa ora ogni giorno" },
  { name: "Moduretic", ingredient: "Amiloride / idroclorotiazide", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Al mattino" },
  { name: "Aldactone", ingredient: "Spironolattone", form: "tablet", typicalDose: 25, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Crestor", ingredient: "Rosuvastatina", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Alla sera" },
  { name: "Ezetrol", ingredient: "Ezetimibe", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Una volta al giorno, con o senza cibo" },
  { name: "Januvia", ingredient: "Sitagliptin", form: "tablet", typicalDose: 100, unit: "mg", instructions: "Una volta al giorno" },
  { name: "Jardiance", ingredient: "Empagliflozin", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Al mattino" },
  { name: "Trulicity", ingredient: "Dulaglutide", form: "injection", typicalDose: 1.5, unit: "mg", instructions: "Una volta a settimana, sottocute" },
  { name: "Ozempic", ingredient: "Semaglutide", form: "injection", typicalDose: 0.5, unit: "mg", instructions: "Una volta a settimana, sottocute" },
  { name: "Glucophage", ingredient: "Metformina", form: "tablet", typicalDose: 1000, unit: "mg", instructions: "A stomaco pieno, durante i pasti" },
  { name: "Diamicron", ingredient: "Gliclazide", form: "tablet", typicalDose: 60, unit: "mg", instructions: "A colazione" },
  { name: "Levemir", ingredient: "Insulina detemir", form: "injection", typicalDose: 10, unit: "UI", instructions: "Sempre alla stessa ora, ruotare il sito" },
  { name: "Humalog", ingredient: "Insulina lispro", form: "injection", typicalDose: 6, unit: "UI", instructions: "Subito prima dei pasti" },
  { name: "Voltaren", ingredient: "Diclofenac", form: "tablet", typicalDose: 50, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Brufen", ingredient: "Ibuprofene", form: "tablet", typicalDose: 600, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Nurofen", ingredient: "Ibuprofene", form: "tablet", typicalDose: 200, unit: "mg", instructions: "A stomaco pieno" },
  { name: "Efferalgan", ingredient: "Paracetamolo", form: "tablet", typicalDose: 1000, unit: "mg", instructions: "A stomaco pieno, non superare 3 g/die" },
  { name: "Toradol", ingredient: "Ketorolac", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Al bisogno, massimo 5 giorni" },
  { name: "Muscoril", ingredient: "Tiocolchicoside", form: "capsule", typicalDose: 4, unit: "mg", instructions: "Due volte al giorno" },
  { name: "Lyrica", ingredient: "Pregabalin", form: "capsule", typicalDose: 75, unit: "mg", instructions: "Due volte al giorno" },
  { name: "Depakin", ingredient: "Acido valproico", form: "tablet", typicalDose: 500, unit: "mg", instructions: "Durante i pasti" },
  { name: "Rivotril", ingredient: "Clonazepam", form: "drops", typicalDose: 2.5, unit: "gocce", instructions: "Secondo prescrizione" },
  { name: "En", ingredient: "Delorazepam", form: "drops", typicalDose: 10, unit: "gocce", instructions: "Secondo prescrizione" },
  { name: "Prozac", ingredient: "Fluoxetina", form: "capsule", typicalDose: 20, unit: "mg", instructions: "Al mattino" },
  { name: "Cipralex", ingredient: "Escitalopram", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Al mattino, con o senza cibo" },
  { name: "Efexor", ingredient: "Venlafaxina", form: "capsule", typicalDose: 75, unit: "mg", instructions: "Al mattino, con cibo" },
  { name: "Seroquel", ingredient: "Quetiapina", form: "tablet", typicalDose: 25, unit: "mg", instructions: "Alla sera" },
  { name: "Risperdal", ingredient: "Risperidone", form: "tablet", typicalDose: 1, unit: "mg", instructions: "Secondo schema del medico" },
  { name: "Aerius", ingredient: "Desloratadina", form: "tablet", typicalDose: 5, unit: "mg", instructions: "Una volta al giorno" },
  { name: "Zirtec", ingredient: "Cetirizina", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Una volta al giorno, alla sera" },
  { name: "Bentelan collirio", ingredient: "Betametasone", form: "drops", typicalDose: 2, unit: "gocce", instructions: "Secondo schema del medico" },
  { name: "Rinazina", ingredient: "Xilometazolina", form: "drops", typicalDose: 2, unit: "gocce", instructions: "Al bisogno, non oltre 5 giorni" },
  { name: "Vicks", ingredient: "Destrometorfano", form: "syrup", typicalDose: 15, unit: "ml", instructions: "Al bisogno per la tosse" },
  { name: "Bisolvon", ingredient: "Bromexina", form: "syrup", typicalDose: 10, unit: "ml", instructions: "Tre volte al giorno" },
  { name: "Singulair", ingredient: "Montelukast", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Alla sera" },
  { name: "Foster", ingredient: "Beclometasone / formoterolo", form: "inhaler", typicalDose: 100, unit: "mcg", instructions: "Due volte al giorno" },
  { name: "Seretide", ingredient: "Fluticasone / salmeterolo", form: "inhaler", typicalDose: 25, unit: "mcg", instructions: "Due volte al giorno" },
  { name: "Spiriva", ingredient: "Tiotropio", form: "inhaler", typicalDose: 18, unit: "mcg", instructions: "Una volta al giorno" },
  { name: "Imodium", ingredient: "Loperamide", form: "capsule", typicalDose: 2, unit: "mg", instructions: "Al bisogno per la diarrea" },
  { name: "Peridon", ingredient: "Domperidone", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Prima dei pasti" },
  { name: "Plasil", ingredient: "Metoclopramide", form: "drops", typicalDose: 20, unit: "gocce", instructions: "Prima dei pasti" },
  { name: "Motilium", ingredient: "Domperidone", form: "tablet", typicalDose: 10, unit: "mg", instructions: "Prima dei pasti" },
  { name: "Colimil", ingredient: "Estratti vegetali", form: "drops", typicalDose: 10, unit: "gocce", instructions: "Dopo i pasti" },
  { name: "Uro-Bec", ingredient: "Mirtillo rosso", form: "capsule", typicalDose: 1, unit: "cps", instructions: "Una volta al giorno" },
  { name: "Vivin C", ingredient: "Acido acetilsalicilico / vitamina C", form: "sachet", typicalDose: 400, unit: "mg", instructions: "Sciogliere in acqua" },
  { name: "Zerinol", ingredient: "Paracetamolo / pseudoefedrina", form: "sachet", typicalDose: 500, unit: "mg", instructions: "Al bisogno per i sintomi da raffreddore" },
  { name: "Neo Borocillina", ingredient: "Benzocaina / cetilpiridinio", form: "tablet", typicalDose: 1, unit: "cpr", instructions: "Sciogliere in bocca, al bisogno" },
  { name: "Prevacid", ingredient: "Lansoprazolo", form: "capsule", typicalDose: 30, unit: "mg", instructions: "Prima di colazione" },
  { name: "Zantac", ingredient: "Ranitidina", form: "tablet", typicalDose: 150, unit: "mg", instructions: "Mattina e sera" },
  { name: "Gaviscon", ingredient: "Alginato di sodio", form: "syrup", typicalDose: 10, unit: "ml", instructions: "Dopo i pasti e prima di coricarsi" },
  { name: "Levoxacin", ingredient: "Levofloxacina", form: "tablet", typicalDose: 500, unit: "mg", instructions: "Una volta al giorno" },
  { name: "Zitromax", ingredient: "Azitromicina", form: "tablet", typicalDose: 500, unit: "mg", instructions: "Una volta al giorno, lontano dai pasti" },
  { name: "Rocefin", ingredient: "Ceftriaxone", form: "injection", typicalDose: 1, unit: "g", instructions: "Intramuscolo, secondo prescrizione" },
  { name: "Bactrim", ingredient: "Sulfametoxazolo / trimetoprim", form: "tablet", typicalDose: 800, unit: "mg", instructions: "Due volte al giorno" },
  { name: "Flagyl", ingredient: "Metronidazolo", form: "tablet", typicalDose: 500, unit: "mg", instructions: "Durante i pasti" },
  { name: "Diflucan", ingredient: "Fluconazolo", form: "capsule", typicalDose: 150, unit: "mg", instructions: "Dose singola o secondo prescrizione" },
  { name: "Aciclovir", ingredient: "Aciclovir", form: "tablet", typicalDose: 400, unit: "mg", instructions: "Cinque volte al giorno durante l'episodio" },
  { name: "Fosamax", ingredient: "Alendronato", form: "tablet", typicalDose: 70, unit: "mg", instructions: "Una volta a settimana, a digiuno, in piedi" },
  { name: "Prolia", ingredient: "Denosumab", form: "injection", typicalDose: 60, unit: "mg", instructions: "Sottocute ogni 6 mesi" },
  { name: "Calcium Sandoz", ingredient: "Calcio carbonato", form: "sachet", typicalDose: 1000, unit: "mg", instructions: "Sciogliere in acqua, durante i pasti" },
  { name: "Magnesio Supremo", ingredient: "Magnesio citrato", form: "sachet", typicalDose: 1, unit: "bustina", instructions: "Sciogliere in acqua, la sera" },
];

export function searchDrugs(query: string): Drug[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return DRUG_CATALOG.filter(
    (d) =>
      d.name.toLowerCase().includes(q) ||
      d.ingredient.toLowerCase().includes(q),
  ).slice(0, 16);
}
