/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as FamigliaRouteImport } from './routes/famiglia'
import { Route as ImpostazioniRouteImport } from './routes/impostazioni'
import { Route as PProfileIdRouteImport } from './routes/p.$profileId'
import { Route as PProfileIdIndexRouteImport } from './routes/p.$profileId/index'
import { Route as PProfileIdDocumentiRouteImport } from './routes/p.$profileId/documenti'
import { Route as PProfileIdParametriRouteImport } from './routes/p.$profileId/parametri'
import { Route as PProfileIdReportRouteImport } from './routes/p.$profileId/report'
import { Route as PProfileIdSintomiRouteImport } from './routes/p.$profileId/sintomi'
import { Route as PProfileIdTerapieRouteImport } from './routes/p.$profileId/terapie'
import { Route as PProfileIdVisiteRouteImport } from './routes/p.$profileId/visite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const FamigliaRoute = FamigliaRouteImport.update({
  id: '/famiglia',
  path: '/famiglia',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniRoute = ImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const PProfileIdRoute = PProfileIdRouteImport.update({
  id: '/p/$profileId',
  path: '/p/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProfileIdIndexRoute = PProfileIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProfileIdRoute,
} as any)
const PProfileIdDocumentiRoute = PProfileIdDocumentiRouteImport.update({
  id: '/documenti',
  path: '/documenti',
  getParentRoute: () => PProfileIdRoute,
} as any)
const PProfileIdParametriRoute = PProfileIdParametriRouteImport.update({
  id: '/parametri',
  path: '/parametri',
  getParentRoute: () => PProfileIdRoute,
} as any)
const PProfileIdReportRoute = PProfileIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PProfileIdRoute,
} as any)
const PProfileIdSintomiRoute = PProfileIdSintomiRouteImport.update({
  id: '/sintomi',
  path: '/sintomi',
  getParentRoute: () => PProfileIdRoute,
} as any)
const PProfileIdTerapieRoute = PProfileIdTerapieRouteImport.update({
  id: '/terapie',
  path: '/terapie',
  getParentRoute: () => PProfileIdRoute,
} as any)
const PProfileIdVisiteRoute = PProfileIdVisiteRouteImport.update({
  id: '/visite',
  path: '/visite',
  getParentRoute: () => PProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/famiglia': typeof FamigliaRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/p/$profileId': typeof PProfileIdRouteWithChildren
  '/p/$profileId/documenti': typeof PProfileIdDocumentiRoute
  '/p/$profileId/parametri': typeof PProfileIdParametriRoute
  '/p/$profileId/report': typeof PProfileIdReportRoute
  '/p/$profileId/sintomi': typeof PProfileIdSintomiRoute
  '/p/$profileId/terapie': typeof PProfileIdTerapieRoute
  '/p/$profileId/visite': typeof PProfileIdVisiteRoute
  '/p/$profileId/': typeof PProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/famiglia': typeof FamigliaRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/p/$profileId/documenti': typeof PProfileIdDocumentiRoute
  '/p/$profileId/parametri': typeof PProfileIdParametriRoute
  '/p/$profileId/report': typeof PProfileIdReportRoute
  '/p/$profileId/sintomi': typeof PProfileIdSintomiRoute
  '/p/$profileId/terapie': typeof PProfileIdTerapieRoute
  '/p/$profileId/visite': typeof PProfileIdVisiteRoute
  '/p/$profileId': typeof PProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/famiglia': typeof FamigliaRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/p/$profileId': typeof PProfileIdRouteWithChildren
  '/p/$profileId/documenti': typeof PProfileIdDocumentiRoute
  '/p/$profileId/parametri': typeof PProfileIdParametriRoute
  '/p/$profileId/report': typeof PProfileIdReportRoute
  '/p/$profileId/sintomi': typeof PProfileIdSintomiRoute
  '/p/$profileId/terapie': typeof PProfileIdTerapieRoute
  '/p/$profileId/visite': typeof PProfileIdVisiteRoute
  '/p/$profileId/': typeof PProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/famiglia'
    | '/impostazioni'
    | '/p/$profileId'
    | '/p/$profileId/documenti'
    | '/p/$profileId/parametri'
    | '/p/$profileId/report'
    | '/p/$profileId/sintomi'
    | '/p/$profileId/terapie'
    | '/p/$profileId/visite'
    | '/p/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/famiglia'
    | '/impostazioni'
    | '/p/$profileId/documenti'
    | '/p/$profileId/parametri'
    | '/p/$profileId/report'
    | '/p/$profileId/sintomi'
    | '/p/$profileId/terapie'
    | '/p/$profileId/visite'
    | '/p/$profileId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/famiglia'
    | '/impostazioni'
    | '/p/$profileId'
    | '/p/$profileId/documenti'
    | '/p/$profileId/parametri'
    | '/p/$profileId/report'
    | '/p/$profileId/sintomi'
    | '/p/$profileId/terapie'
    | '/p/$profileId/visite'
    | '/p/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  FamigliaRoute: typeof FamigliaRoute
  ImpostazioniRoute: typeof ImpostazioniRoute
  PProfileIdRoute: typeof PProfileIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/famiglia': {
      id: '/famiglia'
      path: '/famiglia'
      fullPath: '/famiglia'
      preLoaderRoute: typeof FamigliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni': {
      id: '/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof ImpostazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$profileId': {
      id: '/p/$profileId'
      path: '/p/$profileId'
      fullPath: '/p/$profileId'
      preLoaderRoute: typeof PProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$profileId/': {
      id: '/p/$profileId/'
      path: '/'
      fullPath: '/p/$profileId/'
      preLoaderRoute: typeof PProfileIdIndexRouteImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/documenti': {
      id: '/p/$profileId/documenti'
      path: '/documenti'
      fullPath: '/p/$profileId/documenti'
      preLoaderRoute: typeof PProfileIdDocumentiRouteImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/parametri': {
      id: '/p/$profileId/parametri'
      path: '/parametri'
      fullPath: '/p/$profileId/parametri'
      preLoaderRoute: typeof PProfileIdParametriRouteImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/report': {
      id: '/p/$profileId/report'
      path: '/report'
      fullPath: '/p/$profileId/report'
      preLoaderRoute: typeof PProfileIdReportRouteImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/sintomi': {
      id: '/p/$profileId/sintomi'
      path: '/sintomi'
      fullPath: '/p/$profileId/sintomi'
      preLoaderRoute: typeof PProfileIdSintomiRouteImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/terapie': {
      id: '/p/$profileId/terapie'
      path: '/terapie'
      fullPath: '/p/$profileId/terapie'
      preLoaderRoute: typeof PProfileIdTerapieRouteImport
      parentRoute: typeof PProfileIdRoute
    }
    '/p/$profileId/visite': {
      id: '/p/$profileId/visite'
      path: '/visite'
      fullPath: '/p/$profileId/visite'
      preLoaderRoute: typeof PProfileIdVisiteRouteImport
      parentRoute: typeof PProfileIdRoute
    }
  }
}

interface PProfileIdRouteChildren {
  PProfileIdDocumentiRoute: typeof PProfileIdDocumentiRoute
  PProfileIdParametriRoute: typeof PProfileIdParametriRoute
  PProfileIdReportRoute: typeof PProfileIdReportRoute
  PProfileIdSintomiRoute: typeof PProfileIdSintomiRoute
  PProfileIdTerapieRoute: typeof PProfileIdTerapieRoute
  PProfileIdVisiteRoute: typeof PProfileIdVisiteRoute
  PProfileIdIndexRoute: typeof PProfileIdIndexRoute
}

const PProfileIdRouteChildren: PProfileIdRouteChildren = {
  PProfileIdDocumentiRoute: PProfileIdDocumentiRoute,
  PProfileIdParametriRoute: PProfileIdParametriRoute,
  PProfileIdReportRoute: PProfileIdReportRoute,
  PProfileIdSintomiRoute: PProfileIdSintomiRoute,
  PProfileIdTerapieRoute: PProfileIdTerapieRoute,
  PProfileIdVisiteRoute: PProfileIdVisiteRoute,
  PProfileIdIndexRoute: PProfileIdIndexRoute,
}

const PProfileIdRouteWithChildren = PProfileIdRoute._addFileChildren(
  PProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  FamigliaRoute: FamigliaRoute,
  ImpostazioniRoute: ImpostazioniRoute,
  PProfileIdRoute: PProfileIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
